"""add propery is_album and is_playlist

Revision ID: 22cbf4309327
Revises: e0b5340a3f8a
Create Date: 2024-05-12 21:15:44.918014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22cbf4309327'
down_revision = 'e0b5340a3f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_to_music', sa.Column('is_playlist', sa.Boolean(), nullable=True))
    op.add_column('requests_to_music', sa.Column('is_album', sa.Boolean(), nullable=True))
    op.alter_column('requests_to_music', 'title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests_to_music', 'title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.drop_column('requests_to_music', 'is_album')
    op.drop_column('requests_to_music', 'is_playlist')
    # ### end Alembic commands ###
