"""add propery is_artist and is_one_track

Revision ID: 4d73d6d0bb20
Revises: 22cbf4309327
Create Date: 2024-05-17 16:13:22.892684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d73d6d0bb20'
down_revision = '22cbf4309327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_to_music', sa.Column('is_artist', sa.Boolean(), nullable=True))
    op.add_column('requests_to_music', sa.Column('is_one_track', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests_to_music', 'is_one_track')
    op.drop_column('requests_to_music', 'is_artist')
    # ### end Alembic commands ###
