"""Init models

Revision ID: dd0dabbbb330
Revises: 
Create Date: 2024-01-13 18:15:35.757531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0dabbbb330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('text_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guilds'))
    )
    op.create_index(op.f('ix_guilds_id'), 'guilds', ['id'], unique=False)
    op.create_table('requests_to_music',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request', sa.String(length=300), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_requests_to_music_guild_id_guilds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests_to_music'))
    )
    op.create_index(op.f('ix_requests_to_music_id'), 'requests_to_music', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_to_music_id'), table_name='requests_to_music')
    op.drop_table('requests_to_music')
    op.drop_index(op.f('ix_guilds_id'), table_name='guilds')
    op.drop_table('guilds')
    # ### end Alembic commands ###
