"""add propery title

Revision ID: e0b5340a3f8a
Revises: dd0dabbbb330
Create Date: 2024-05-12 20:48:57.650465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0b5340a3f8a'
down_revision = 'dd0dabbbb330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_to_music', sa.Column('title', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests_to_music', 'title')
    # ### end Alembic commands ###
