"""add user_name_playlist and album_name_track

Revision ID: fa4f62849fd9
Revises: 4d73d6d0bb20
Create Date: 2024-05-21 20:10:02.193704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa4f62849fd9'
down_revision = '4d73d6d0bb20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_to_music', sa.Column('user_name_playlist', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('requests_to_music', sa.Column('album_name_track', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('requests_to_music', sa.Column('name_command', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests_to_music', 'user_name_playlist')
    op.drop_column('requests_to_music', 'album_name_track')
    op.drop_column('requests_to_music', 'name_command')
    # ### end Alembic commands ###
